# Create user
POST http://localhost:3001/auth/signup HTTP/1.1
content-type: application/json

{
    "username": "user100",
    "email": "user100@example.org",
    "password": "password1"
}

###

# Log-in
POST http://localhost:3001/auth/login HTTP/1.1
content-type: application/json

{
    "username": "user100@example.org",
    "password": "password1"
}

###

# Bad log-in
POST http://localhost:3001/auth/login HTTP/1.1
content-type: application/json

{
    "username": "user1",
    "password": "badpassword"
}

### 
# ** Test **

# Create user
POST https://shy-tan-meerkat-garb.cyclic.app/auth/signup HTTP/1.1
content-type: application/jsongit 

{
    "username": "user1",
    "password": "password1"
}

###

# Log-in
POST https://shy-tan-meerkat-garb.cyclic.app/auth/login HTTP/1.1
content-type: application/json

{
    "username": "user1",
    "password": "password1"
}